[configuration]
config_file = /home/marcelo_baez/paccanaro-lab/S2F/s2f.conf
alias = cafa3_testset
obo = /home/marcelo_baez/paccanaro-lab/S2F/go.obo
fasta = /media/marcelo_baez/HD_Disc1/databases/ProjectData/cafa3/S2F/test_set.fasta

[graphs]
combined_graph = compute
graph_collection = /media/marcelo_baez/HD_Disc1/.S2F/graphs/collection/cafa3_testset
homology_graph = compute
recompute_orthologs = false
collection_chunk_size = 600000

[seeds]
interpro_output = compute
hmmer_output = compute
foldseek_output = skip
plm_output = skip
alpha = 0.9
beta = 0.1
gamma = 0.0

[foldseek]
target_db =
structure_mode = existing
structures_dir = structures
precomputed_tsv =
search_recursive = false
prostt5_model =
gpu =
cuda_visible_devices =
alignment_type = 1
evalue_max = 1e-5
min_qcov = 0.70
min_tcov = 0.70
min_avg_tm = 0.50
max_seqs = 0
score_mode = binary

[plm]
target_fasta =
model_name = facebook/esm1b_t33_650M_UR50S
model_dir =
embeddings_dir =
device = auto
knn_k = 10
long_sequence_mode = sliding_mean
long_window_size = 1022
long_overlap = 128
score_mode = all_ones
batch_tokens = 4096
query_chunk_size = 64
local_files_only = false
precomputed_target_embeddings =
precomputed_query_embeddings =
force_target_embeddings = false
force_query_embeddings = false

[blacklists]
hmmer_blacklist = compute
transfer_blacklist = compute

[functions]
goa_clamp = compute
